version: '3'
services:
  app:
    container_name: "bot"
    build:
      dockerfile: docker/Dockerfile
      context: ../
      args:
        STAGE: dev
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    env_file:
      - ../.env
